### ISSUE TITLE
SDVX AC style knobs jittery

### ISSUE THREAD

**Issue by ASleepyCat** [veroxzik/roxy-firmware#1]
On my SVSE5 and arcin, using the `arcin-sdvx-ac-nolight` firmware from [here](https://github.com/theKeithD/arcin/tree/sv3c-kb/bin), the knob inputs stay perfectly still when configuring analogue inputs. roxy-firmware, however, has jittering at rest. Tested with `320268d23f0ba3d3e1dc8829553e493c70e0e589` and jittering still occurs.

**Comment by veroxzik** [comment]
Thanks for the report.
I've been preparing an update that adds a deadzone angle. Do you think this will remedy the issue? Based on my read, that's what theKeithD's code does (it ignores very small deltas).

I can likely have a build ready to test today or tomorrow.

**Comment by ASleepyCat** [comment]
I think so, the lack of a dead zone is the first thing that comes to mind for the jitter. I'll be free to test out a build.

**Comment by veroxzik** [comment]
Decided to publish them as full updates:

https://github.com/veroxzik/roxy-firmware/releases/tag/v0.14
https://github.com/veroxzik/roxy-tool/releases/tag/v1.6.0

Please let me know if this resolves your issue.

**Comment by ASleepyCat** [comment]
Still jittery, even when I set the deadzone to 255. I also tested this yesterday by hard coding the deadzone angle in the firmware and got the same thing.

**Comment by veroxzik** [comment]
Please give this build a shot: [arcin-roxy.zip](https://github.com/veroxzik/roxy-firmware/files/7655351/arcin-roxy.zip)

I copied over all the ADC stuff from the build you linked, as well as fixed a rather dumb bug on my part that was using the raw axis value instead of the filtered value when you had sensitivity set to 1:1 (which you should for AC knobs).

I tested on my AC knobs and it appears the jittering is gone, although oddly only Y is working for me. I don't think it's a code thing, but we'll see.

**Comment by ASleepyCat** [comment]
With a deadzone angle of 6, it seems to have resolved the jitter. There's an issue where the rotation values are skipping 48 and 49% in spicecfg. Sometimes it skips 49 and 50% instead. However, I think I was facing this issue in a previous firmware.

**Comment by veroxzik** [comment]
I'm going to mark this as resolved since the jitter seems to be good as of release v0.14a. 
If the skipping in spicecfg presents an issue in gameplay, feel free to open a new issue for me to investigate.

Thanks again for your time and testing!
